generator:
  target: face2anime.modules.generators.BaseGenerator
  img_channels: 3
  channels: 64
  block: "Residual"
  n_layer_blocks: 1
  channel_multipliers: [1, 2, 4, 4]
  attention: None

discriminator:
  target: face2anime.modules.discriminators.BaseDiscriminator
  img_channels: 3
  out_channels: 1
  channels: 64
  block: "Residual"
  n_layer_blocks: 1
  channel_multipliers: [1, 2, 4, 4]
  attention: None

training:
  seed: 42
  batch_size: 32
  epochs: 200
  learning_rate: 5e-5
  weight_decay: 0.0000001
  warmup_generator_steps: 0
  precision: 16-mixed
  check_val_every_n_epoch: 10
  pool_size: 50

data:
  root: data
  prefix_a: face_photo
  prefix_b: face_cartoon/kyoto_face
  image_size: 64
